### ISSUE TITLE
Fork sayısı hatası 

### ISSUE THREAD

**Issue by mrokt** [alpcanaydin/github-stats-for-turkey#1]
![ekran resmi 2017-04-10 22 46 09](https://cloud.githubusercontent.com/assets/10600157/24879587/10342360-1e40-11e7-8f1e-5c6ab33d2b98.png)

![ekran resmi 2017-04-10 22 46 14](https://cloud.githubusercontent.com/assets/10600157/24879596/13a2fdc8-1e40-11e7-85d4-d5bf22010fe8.png)

Hocam öncelikle sistem şahane olmuş. Küçük bir hata gördüm paylaşmak istedim.
 İlk fotoğrafta sistem üzerinde VeujsIMDB adlı repo'da fork 0 gözüküyor.
Ancak depoda 1 adet fork bulunmakta. Neden 1 görünmüyor ?

(Hata değilse açtığım için kusura bakmayın)

**Comment by alpcanaydin** [comment]
Teşekkür ederim, sanırım bu fork 8 nisandan sonra gerçekleşmiş. Veri en son 8 nisanda çekildi :)

**Comment by mrokt** [comment]
Tam 8 nisanda idi sanırım hocam. Olabilir ben sadece söylemek istedim. Dediğim gibi süper emeğinize sağlık.

**Comment by alpcanaydin** [comment]
O zaman saatini tutturamamışız veri çekildikten sonra fork olmuş :) Teşekkürler tekrar.
