### ISSUE TITLE
My data not found

### ISSUE THREAD

**Issue by ertugrulungor** [alpcanaydin/github-stats-for-turkey#12]
Hello, I change my location 1 week ago but still not found.

**Comment by ssdwho** [comment]
> Veri en son 8 Nisan 2017 tarihinde çekilmiştir.

Ayda bir yenileyecekler galiba

**Comment by onuragtas** [comment]
Bence 2 yılda bir güncelleyecekler...

**Comment by onur** [comment]
Malatya'yı marjinal şehir yapacağım, fingers crossed bekliyorum :-)

**Comment by ismailtasdelen** [comment]
Güncelleyecekleri yok bence nisan ayından beri güncelleme yapmadılar dataları 👎

**Comment by yunuskorkmaz** [comment]
Yeni bir güncelleme gerekiyor
