### ISSUE TITLE
net::ERR_INSECURE_RESPONSE Sorunu

### ISSUE THREAD

**Issue by abdurrahmanekr** [alpcanaydin/github-stats-for-turkey#16]
Merhabalar @alpcanaydin, sanırsam son 1 - .5 ay içinde projeye girmemiştim fakat bugün yani 6 Ağustos'ta listeye girmeye çalıştığımda bu hata ile karşılaşıyorum. Hatanın ekran görüntüleri: 
<img width="608" alt="ekran resmi 2017-08-06 os 7 32 56" src="https://user-images.githubusercontent.com/15075759/29005175-1d023bea-7ade-11e7-86d5-21f87225ef56.png">
Sorunun kaynağını araştırdım fakat bir sonuca varamadım.

**Comment by alpcanaydin** [comment]
SSL süresi dolduğu için böyle bir hata çıkıyordu düzelttim şimdi teşekkürler bildirim için :)
